apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  labels:
    {{- include "azure-key-vault-helper.labels" . | nindent 4 }}
  name: {{ include "azure-key-vault-helper.fullname" . }}
  namespace: {{ .Values.namespace }}  
spec:
  parameters:
    cloudName: ""
    keyvaultName: {{ .Values.keyVaultName }} 
    objects: |
      array:
        - |
        {{- range $k, $v :=  .Values.objects }}
          objectName: {{ $k }}
        {{- range $objectK, $objectV :=  $v }}
          {{ $objectK }}: {{ $objectV }}
        {{- end }}
        {{- end }}
    tenantId: {{ .Values.tenantId }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.userAssignedIdentityID }} 
  provider: azure
  {{- if .Values.secretObjects }}
  secretObjects:
    {{- range $k, $v := .Values.secretObjects }}
    - secretName: {{ $k }}
      type: {{ $v.type }}
      data:
        {{- range $keyK, $keyV := $v.keys }}
      - key: {{ $keyK }}
        objectName: {{ $keyV }}
        {{- end }}
        
    {{- if $v.labels }}
      labels:
        {{- range $key, $value := $v.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    {{- end }}  
    {{- end }}  
  {{- end }}  
