apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
    {{- include "azure-key-vault-helper.labels" . | nindent 4 }}
  name: {{ include "azure-key-vault-helper.fullname" . }}-key-vault-helper
  namespace: {{ .Values.namespace }}  
spec:
  parameters:
    cloudName: ""
    keyvaultName: {{ .Values.keyVaultName }} 
    objects: |
      array:
      {{- range .Values.objects }}
        - |
          objectName: {{ .name }}
          objectType: {{ .type }}
          objectAlias: {{ .alias }}
      {{- end}}
    tenantId: {{ .Values.tenantId }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.userAssignedIdentityID }} 
  provider: azure
  {{- if .Values.secretObjects }}
  secretObjects:
    {{- range .Values.secretObjects }}
    - data:
        {{- range .data }}
      - key: {{ .key }}
        objectName: {{ .objectName }}
        {{- end }}
      secretName: {{ .secretName }}
      type: {{ .type }}
    {{- if .labels }}
      labels:
        {{- range $key, $value := .labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    {{- end }}  
    {{- end }}  
  {{- end }}  
