{{- if (and .Values.secretsMounter.enabled ) }}
kind: Pod
apiVersion: v1
metadata:
  labels:
    {{- include "azure-key-vault-helper.labels" . | nindent 4 }}
  name: {{ include "azure-key-vault-helper.fullname" . }}
  namespace: {{ .Values.namespace }}  
spec:
  containers:
    - name: {{ include "azure-key-vault-helper.fullname" . }}
      image: {{ .Values.secretsMounter.image.repository }}:{{ .Values.secretsMounter.image.tag }}
      volumeMounts:
      - name: secrets-store01-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
      securityContext:
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: {{ include "azure-key-vault-helper.fullname" . }}
{{- end }}