apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azure-key-vault-helper.fullname" . }}
  labels:
    {{- include "azure-key-vault-helper.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}  
spec:
  replicas: {{ .Values.secretsMounter.replicaCount }}
  selector:
    matchLabels:
      {{- include "azure-key-vault-helper.selectorLabels" . | nindent 6 }}  
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "azure-key-vault-helper.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.secretsMounter.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.secretsMounter.securityContext | nindent 12 }}
          image: {{ .Values.secretsMounter.image.repository }}:{{ .Values.secretsMounter.image.tag }}
          imagePullPolicy: {{ .Values.secretsMounter.image.pullPolicy }}
          resources:
            {{- toYaml .Values.secretsMounter.resources | nindent 12 }}
          volumeMounts:
          - name: secrets-store01-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ include "azure-key-vault-helper.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAffinityPreset "component" "master" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "component" "master" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

