# Default values for azure-key-vault-helper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default
keyVaultName: "my-keyvault-name"
tenantId: "tenant-id"
userAssignedIdentityID: "user-assigned-identity-id"

objects: {}
  # root-ca: #objectName
  #   objectType: secret #objectType
  #   # objectAlias: alias-name # objectAlias
  # other-object-name: #objectName
  #   objectType: secret #objectType
  #   # objectAlias: other-alias-name # objectAlias

secretsMounter: 
  enabled: true
  replicaCount: 2
  image: 
    repository: "kvalitetsit/go-loop"
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    allowPrivilegeEscalation: false
  resources: 
    requests:
      cpu: 10m
      memory: 3Mi

secretObjects: {}
  # ca: # name of secret
  #   keys: # list of keys in secret. 
  #     tls.crt: root-ca # secret key and object name/alias from keyvault
  #     other.key: another-key 
  #   labels: 
  #     label1: "label1_1"
  #     label2: "label2_2"
  #   type: Opaque
  # other-secret: # name of secret
  #   keys: # list of keys in secret. 
  #     key: other-object-name # secret key and object name/alias from keyvault
  #   type: Opaque

## @param operator.podAffinityPreset Pod affinity preset
## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
## Allowed values: soft, hard
##
podAffinityPreset: ""

## @param operator.podAntiAffinityPreset Pod anti-affinity preset.
## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
## Allowed values: `soft` or `hard`
##
podAntiAffinityPreset: "soft"

## Node affinity preset
## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
##
nodeAffinityPreset:
  ## @param operator.nodeAffinityPreset.type Node affinity preset type. Allowed values: `soft` or `hard`
  ##
  type: ""
  ## @param operator.nodeAffinityPreset.key Set nodeAffinity preset key
  ## E.g.
  ## key: "kubernetes.io/e2e-az-name"
  ##
  key: ""
  ## @param operator.nodeAffinityPreset.values Set nodeAffinity preset values
  ## E.g.
  ## values:
  ##   - e2e-az1
  ##   - e2e-az2
  ##
  values: []
